# Generated by Django 5.1.6 on 2026-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(choices=[('kira_road', 'Kira Road'), ('kampala_boulevard', 'Kampala Boulevard'), ('oasis_mall', 'Oasis Mall'), ('nakawa', 'Nakawa'), ('namirembe', 'Namirembe'), ('lugogo', 'Lugogo'), ('bombo_road', 'Bombo Road'), ('parliamentary_avenue', 'Parliamentary Avenue'), ('victoria_mall_entebbe', 'Victoria Mall, Entebbe')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.IntegerField(choices=[(1, '1 Person'), (2, '2 People'), (3, '3 People'), (4, '4 People'), (5, '5 People'), (6, '6 People'), (10, '7 – 10 People'), (11, '11+ People (Group)')], default=2)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table Booking',
                'verbose_name_plural': 'Table Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
