# Generated by Django 5.1.6 on 2026-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('breakfast', 'Breakfast'), ('mains', 'Mains'), ('drinks', 'Drinks'), ('desserts', 'Desserts')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('emoji', models.CharField(max_length=10)),
                ('img', models.URLField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
