# Generated by Django 6.0.3 on 2026-03-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch_name', models.CharField(choices=[('kira_road', 'Kira Road'), ('kampala_boulevard', 'Kampala Boulevard'), ('oasis_mall', 'Oasis Mall'), ('nakawa', 'Nakawa'), ('namirembe', 'Namirembe'), ('lugogo', 'Lugogo'), ('bombo_road', 'Bombo Road'), ('parliamentary_avenue', 'Parliamentary Avenue'), ('victoria_mall_entebbe', 'Victoria Mall, Entebbe')], max_length=50)),
                ('rating', models.IntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'customerFeedback',
                'verbose_name_plural': 'customerFeedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
